services:
  influxdb18:
    image: influxdb:1.8.10
    environment:
      DOCKER_INFLUXDB_INIT_USERNAME: influx
      DOCKER_INFLUXDB_INIT_PASSWORD: aboba123
    volumes:
      - influx18:/var/lib/influxdb
    ports:
      - "8086:8086"

  telegraf:
    image: telegraf:1.25
    environment:
      INFLUX_URL: http://influxdb18:8086
      INFLUX_USERNAME: influx
      INFLUX_PASSWORD: aboba123
      INFLUX_DB: telegraf
      UDP_LINE_PORT: 8094
      UDP_JSON_PORT: 8095
      TCP_LINE_PORT: 8094
      TCP_JSON_PORT: 8095
    ports:
      - "8094:8094/udp"
      - "8095:8095/udp"
      - "8094:8094/tcp"
      - "8095:8095/tcp"
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf

  grafana:
    image: grafana/grafana:latest
    user: "1000" # you might want to change to your UID if you have exotic configuration
    volumes:
      - ./grafana-storage:/var/lib/grafana
    ports:
      - 3000:3000

volumes:
  influx18:
